name: bloc_ui_annotation
description: "Annotations to be used with bloc_ui_generator"
version: 1.0.0
repository: https://github.com/MaxiSonntag/bloc_ui_generator/tree/main/bloc_ui_annotation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
