name: Publish to pub.dev

on:
  push:
    branches: [ "main" ]
jobs:
  install-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
  build-annotations:
    runs-on: ubuntu-latest
    needs: [install-flutter]
    steps:
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./bloc_ui_annotation
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
        working-directory: ./bloc_ui_annotation
  build-generator:
    runs-on: ubuntu-latest
    needs: [install-flutter]
    steps:
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./bloc_ui_generator
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
        working-directory: ./bloc_ui_generator
  publish-annotations:
    runs-on: ubuntu-latest
    needs: [build-annotations, build-generator]
    steps:
      - name: Publish annotations
        uses: k-paxian/dart-package-publisher@master
        with:
          relativePath: ./bloc_ui_annotation
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          skipTests: true
  publish-generator:
    runs-on: ubuntu-latest
    needs: [build-annotations, build-generator]
    steps:
      - name: Publish generator
        uses: k-paxian/dart-package-publisher@master
        with:
          relativePath: ./bloc_ui_generator
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          skipTests: true
